# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_wolfram:
    name: Run Wolfram language code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Wolfram script
      uses: miRoox/wolfram-action@master
      with:
        file: uwu.wls
      env:
        WOLFRAM_ID: ${{ secrets.WOLFRAMID }}
        WOLFRAM_PASS: ${{ secrets.WOLFRAMPW }}
